For Colab only!

In [5]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [1]:
import tensorflow as tf

In [2]:
import torch

In [3]:
print(tf.__version__)
print(tf.test.is_gpu_available())

2.0.0
False


In [4]:
print(torch.__version__)
print(torch.cuda.is_available())

1.4.0
False


#### Scalar Vector and Tensor

In [27]:
#  dim = 0 
a = tf.constant(2.4)
print(a.shape)
print(len(a.shape))
print(a)

# dim = 1 
a = tf.constant([2.4])
print(a)
print("dim = ",len(a.shape))

# dim = 2
b = tf.constant([[1,2],[3,4]])
print(b)
print("dim = ",len(b.shape))

c = tf.constant([[[1,2],[3,4]]])
print(c)
print("dim = ",len(c.shape))

d = tf.constant([[[1],[2]],[[3],[4]]])
print(d)
print("dim = ",len(d.shape))


()
0
tf.Tensor(2.4, shape=(), dtype=float32)
tf.Tensor([2.4], shape=(1,), dtype=float32)
dim =  1
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
dim =  2
tf.Tensor(
[[[1 2]
  [3 4]]], shape=(1, 2, 2), dtype=int32)
dim =  3
tf.Tensor(
[[[1]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)
dim =  3


In [28]:
#  dim = 0 
a = torch.tensor(2.4)
print(a.shape)
print(len(a.shape))
print(a)

# dim = 1 
a = torch.tensor([2.4])
print(a)
print("dim = ",len(a.shape))

# dim = 2
b = torch.tensor([[1,2],[3,4]])
print(b)
print("dim = ",len(b.shape))

c = torch.tensor([[[1,2],[3,4]]])
print(c)
print("dim = ",len(c.shape))

d = torch.tensor([[[1],[2]],[[3],[4]]])
print(d)
print("dim = ",len(d.shape))


torch.Size([])
0
tensor(2.4000)
tensor([2.4000])
dim =  1
tensor([[1, 2],
        [3, 4]])
dim =  2
tensor([[[1, 2],
         [3, 4]]])
dim =  3
tensor([[[1],
         [2]],

        [[3],
         [4]]])
dim =  3


* A tf.Variable represents a tensor whose value can be changed by running ops on it. Specific ops allow you to read and modify the values of this tensor.

* A torch.Tensor can initialize tensor with certain shape. But this is not a recommded initialization methode

In [29]:
#  dim = 0 
a = tf.Variable(2.4)
print(a.shape)
print(len(a.shape))
print(a)

# dim = 1 
a = tf.Variable([2.4])
print(a)
print("dim = ",len(a.shape))

# dim = 2
b = tf.Variable([[1,2],[3,4]])
print(b)
print("dim = ",len(b.shape))

c = tf.Variable([[[1,2],[3,4]]])
print(c)
print("dim = ",len(c.shape))

d = tf.Variable([[[1],[2]],[[3],[4]]])
print(d)SS
print("dim = ",len(d.shape))


()
0
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=2.4>
<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([2.4], dtype=float32)>
dim =  1
<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>
dim =  2
<tf.Variable 'Variable:0' shape=(1, 2, 2) dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>
dim =  3
<tf.Variable 'Variable:0' shape=(2, 2, 1) dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>
dim =  3


In [71]:
# dim = 1
x = torch.Tensor(1)
print(x)
print('dim = ', len(x.shape))


# dim = 2
x = torch.IntTensor(2,3)
print(x)
print('dim = ', len(x.shape))

# dim = 3
x = torch.FloatTensor(2,3,4)
print(x)
print(x.shape)
print('dim = ', len(x.shape))

x = torch.empty(2,3,4)
print(x)
print(x.shape)
print('dim = ', len(x.shape))

tensor([7.0065e-45])
dim =  1
tensor([[        0,         0,         0],
        [        0, 919118944,         1]], dtype=torch.int32)
dim =  2
tensor([[[ 0.0000e+00, -2.5244e-29,  0.0000e+00, -2.5244e-29],
         [ 1.6816e-44,  0.0000e+00,  6.0616e-06,  1.4013e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 5.9796e-06,  1.4013e-45,         nan,  0.0000e+00],
         [ 1.4013e-45,  0.0000e+00,         nan,  2.2369e+08],
         [ 6.0603e-06,  1.4013e-45,  1.4013e-45,  5.5101e-40]]])
torch.Size([2, 3, 4])
dim =  3
tensor([[[ 2.3694e-38,  2.3694e-38,  2.3694e-38,  2.3511e-38],
         [ 2.3511e-38,  2.3694e-38,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00, -2.5244e-29,  1.7496e+18, -8.5920e+09]],

        [[ 9.8091e-45,  0.0000e+00,  6.0616e-06,  1.4013e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 5.9796e-06,  1.4013e-45,         nan,  2.5250e-29]]])
torch.Size([2, 3, 4])
dim =  3


In [45]:
tf.Variable()

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=2>

#### Tensor Initialize
* From numpy or list
* All one/zero/eye
* Random normal/uniform

In [46]:
import numpy as np

In [66]:
a = np.array([1,2,3])
aa = tf.Variable(a)
print(aa)

# back to numpy
print(aa.numpy())

b = tf.ones(shape=[3,3])
print(b)

c = tf.zeros(shape=[1,2,3])
print(c)

d = tf.eye(4)
print(d)

e = tf.random.uniform([3,3],
                     minval=-1,
                     maxval= 1)
print(e)

f = tf.random.normal([3,3])
print(f)



<tf.Variable 'Variable:0' shape=(3,) dtype=int64, numpy=array([1, 2, 3])>
[1 2 3]
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[-0.10190296 -0.643075    0.42584777]
 [-0.9554393   0.6987076  -0.3890078 ]
 [-0.06272173  0.40875173 -0.7274647 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[-0.25065485  1.7940968   0.55680776]
 [ 0.6731767  -2.0355575   0.69362056]
 [ 0.56592643 -0.21413745  1.4197971 ]], shape=(3, 3), dtype=float32)


In [75]:
a = np.array([1,2,3])
aa = torch.from_numpy(a)
print(aa)

# back to numpy
print(aa.numpy())

b = torch.ones([3,3])
print(b)

c = torch.zeros([1,2,3])
print(c)

d = torch.eye(4)
print(d)

e = torch.rand([3,3]) *2 -1
print(e)

f = torch.empty(3,3)
f = f.normal_()
print(f)

g = torch.rand_like(e)
print(g)


tensor([1, 2, 3])
[1 2 3]
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
tensor([[ 0.9732,  0.5554, -0.2643],
        [-0.2719,  0.4748, -0.9342],
        [ 0.2863, -0.9117,  0.8118]])
tensor([[ 0.3644, -0.3464,  0.3899],
        [-0.7579, -0.4579, -0.7229],
        [-0.1353, -0.1644, -1.0985]])
tensor([[0.8672, 0.4170, 0.2993],
        [0.2276, 0.8151, 0.8255],
        [0.1173, 0.7587, 0.2998]])


#### Indexing and slicing

start : end: step (end is not included)

In [92]:
x = tf.random.uniform([2,28,28,3])

print(x[0][0][0])
print(x[0,0,0])
print(x[0,0,0,:])

print(x[0,:,0,0].shape)

print(x[1,::2,::2,1].shape)

print(x[0,...,0].shape)

tf.Tensor([0.30244088 0.48277724 0.66974723], shape=(3,), dtype=float32)
tf.Tensor([0.30244088 0.48277724 0.66974723], shape=(3,), dtype=float32)
tf.Tensor([0.30244088 0.48277724 0.66974723], shape=(3,), dtype=float32)
(28,)
(14, 14)
(28, 28)


In [95]:
x = torch.rand([2,3,28,28])
print(x[0][0][0])
print(x[0,0,0])
print(x[0,0,0,:].shape)

print(x[0,1,::2,::2].shape)

print(x[0,...,0].shape)

tensor([0.2286, 0.0121, 0.3937, 0.0671, 0.4020, 0.3109, 0.2263, 0.6636, 0.1600,
        0.6500, 0.7802, 0.2829, 0.2400, 0.1953, 0.6289, 0.0833, 0.9539, 0.1139,
        0.2049, 0.1019, 0.2217, 0.3020, 0.4510, 0.1544, 0.4524, 0.9684, 0.8236,
        0.4322])
tensor([0.2286, 0.0121, 0.3937, 0.0671, 0.4020, 0.3109, 0.2263, 0.6636, 0.1600,
        0.6500, 0.7802, 0.2829, 0.2400, 0.1953, 0.6289, 0.0833, 0.9539, 0.1139,
        0.2049, 0.1019, 0.2217, 0.3020, 0.4510, 0.1544, 0.4524, 0.9684, 0.8236,
        0.4322])
torch.Size([28])
torch.Size([14, 14])
torch.Size([3, 28])


### Reshape

Image shape: [b, w, h, c]

In [107]:
x = tf.random.uniform([5,28,28,3])

print(tf.reshape(x, [5, 28*28, 3]).shape)
print(tf.reshape(x, [5, 14, 56, 3]).shape)

print(x.shape)

print(tf.expand_dims(x, axis=0).shape)

y = tf.expand_dims(x, axis=2)
print(tf.squeeze(y, axis=2).shape)

print(x.shape)


(5, 784, 3)
(5, 14, 56, 3)
(5, 28, 28, 3)
(1, 5, 28, 28, 3)
(5, 28, 28, 3)
(5, 28, 28, 3)


In [101]:
x = torch.rand([5,3,28,28])

print(x.view(5,3,28*28).shape)
print(x.view(5,3,14,56).shape)

print(x.shape)

torch.Size([5, 3, 784])
torch.Size([5, 3, 14, 56])
torch.Size([5, 3, 28, 28])
