### Initialization

In [1]:
# For Colab only!

try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [2]:
import tensorflow as tf

In [3]:
import torch

In [4]:
print(tf.__version__)
print(tf.test.is_gpu_available())

2.0.0
False


In [5]:
print(torch.__version__)
print(torch.cuda.is_available())

1.4.0
False


### Basic

elementwise

**"  + - * /  "**



In [17]:
#  "+ - * /"
#  add subtract multiply div
a = tf.random.uniform([3,4])
b = tf.random.uniform([4])

print(a+b)
print(tf.add(a,b).shape)

print(a-b)
print(tf.subtract(a,b).shape)

print(a*b)
print(tf.multiply(a,b).shape)

print(a/b)
print(tf.divide(a,b).shape)

tf.Tensor(
[[0.88811684 1.0461007  1.415938   0.3643744 ]
 [0.63458323 0.8540065  1.619497   0.7716217 ]
 [0.9911736  1.6366682  1.2705028  0.6875068 ]], shape=(3, 4), dtype=float32)
(3, 4)
tf.Tensor(
[[ 0.7327397  -0.6465975  -0.2164098  -0.2110796 ]
 [ 0.4792061  -0.8386917  -0.01285088  0.1961677 ]
 [ 0.8357965  -0.05603004 -0.36184502  0.1120528 ]], shape=(3, 4), dtype=float32)
(3, 4)
tf.Tensor(
[[0.06296102 0.1690596  0.48951182 0.02205353]
 [0.04326435 0.00648084 0.6556513  0.13922957]
 [0.07096735 0.6688859  0.3708114  0.11502744]], shape=(3, 4), dtype=float32)
(3, 4)
tf.Tensor(
[[1.0431756e+01 2.3601562e-01 7.3484844e-01 2.6638931e-01]
 [7.1682954e+00 9.0475772e-03 9.8425472e-01 1.6817842e+00]
 [1.1758293e+01 9.3379796e-01 5.5665696e-01 1.3894414e+00]], shape=(3, 4), dtype=float32)
(3, 4)


In [19]:
#  "+ - * /"
#  add sub mul div
a = torch.rand(3,4)
b = torch.rand(4)

print(a+b)
print(torch.add(a,b).shape)

print(a-b)
print(torch.sub(a,b).shape)

print(a*b)
print(torch.mul(a,b).shape)

print(a/b)
print(torch.div(a,b).shape)

tensor([[0.9128, 0.7211, 0.5927, 1.0332],
        [0.6215, 0.7827, 0.8588, 0.6937],
        [1.2285, 1.1786, 0.5472, 0.7542]])
torch.Size([3, 4])
tensor([[-0.2044, -0.1169,  0.3485,  0.2551],
        [-0.4957, -0.0553,  0.6146, -0.0844],
        [ 0.1113,  0.3407,  0.3029, -0.0239]])
torch.Size([3, 4])
tensor([[0.1979, 0.1266, 0.0575, 0.2506],
        [0.0351, 0.1524, 0.0899, 0.1185],
        [0.3742, 0.3183, 0.0519, 0.1421]])
torch.Size([3, 4])
tensor([[0.6341, 0.7210, 3.8541, 1.6557],
        [0.1126, 0.8679, 6.0330, 0.7831],
        [1.1992, 1.8130, 3.4810, 0.9385]])
torch.Size([3, 4])


### MatMul
1. @
2. matmul


In [28]:
a = tf.random.uniform([3,4])
b = tf.random.uniform([4,3])

print(a@b)
print(tf.matmul(a,b))

# Example: image x [2, 784] -> [2, 256]
# w: [in, out]
# b: [out]

x = tf.random.uniform([2,784])
w = tf.random.uniform([784,256])
b = tf.zeros([256])

out = x@w + b
print(out.shape)

tf.Tensor(
[[0.7213653  1.0957313  0.71883625]
 [1.2929616  1.3000406  1.0615227 ]
 [1.2351133  1.4739505  1.2573469 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[0.7213653  1.0957313  0.71883625]
 [1.2929616  1.3000406  1.0615227 ]
 [1.2351133  1.4739505  1.2573469 ]], shape=(3, 3), dtype=float32)
(2, 256)


In [29]:
a = torch.rand(3,4)
b = torch.rand(4,3)

print(a@b)
print(torch.matmul(a,b))

# Example: image x [2, 784] -> [2, 256]
# w: [out, in],  w.t() transpose 
# b: [out]

x = torch.rand(2, 784)
w = torch.rand(256, 784)
b = torch.zeros(256)

out = x@w.t() + b
print(out.shape)

tensor([[1.3314, 0.8028, 1.6500],
        [0.9878, 0.9880, 1.2405],
        [1.1633, 0.9607, 1.3768]])
tensor([[1.3314, 0.8028, 1.6500],
        [0.9878, 0.9880, 1.2405],
        [1.1633, 0.9607, 1.3768]])
torch.Size([2, 256])


#### Dim over 2

Only MatMul the last two dimentions

In [40]:
a = tf.random.uniform([2,3,28,12])
b = tf.random.uniform([2,3,12,28])

print((a@b).shape)
print(tf.matmul(a,b).shape)

# automatic broadcasting
# c [12, 14] -> [1,1,12,14] ->[2,3,12,14]
c = tf.random.uniform([12,14])
print((a@c).shape)

(2, 3, 28, 28)
(2, 3, 28, 28)
(2, 3, 28, 14)


In [43]:
a = torch.rand(2,3,28,12)
b = torch.rand(2,3,12,28)

print((a@b).shape)
print(torch.matmul(a,b).shape)

# automatic broadcasting
# c [12, 14] -> [1,1,12,14] ->[2,3,12,14]
c = torch.rand(12,14)
print((a@c).shape)

torch.Size([2, 3, 28, 28])
torch.Size([2, 3, 28, 28])
torch.Size([2, 3, 28, 14])


### Power and log
elemente-wise: pow sqll **

In [66]:
a = tf.fill([3,3],9.0)
print(a**2)
print(tf.pow(a, 2))
print(a**0.5)
print(tf.sqrt(a))

b = tf.ones([3,3])*2
c = tf.exp(b)
d = tf.math.log(c)
print(b, c, d)

tf.Tensor(
[[81. 81. 81.]
 [81. 81. 81.]
 [81. 81. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[81. 81. 81.]
 [81. 81. 81.]
 [81. 81. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2.9999998 2.9999998 2.9999998]
 [2.9999998 2.9999998 2.9999998]
 [2.9999998 2.9999998 3.       ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float32) tf.Tensor(
[[7.389056 7.389056 7.389056]
 [7.389056 7.389056 7.389056]
 [7.389056 7.389056 7.389056]], shape=(3, 3), dtype=float32) tf.Tensor(
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]], shape=(3, 3), dtype=float32)


In [65]:
a = torch.full([3,3],9)
print(a**2)
print(torch.pow(a,2))
print(a**0.5)
print(torch.sqrt(a))

b = torch.ones([3,3])*2
c = torch.exp(b)
d = torch.log(c)
print(b, c, d)

tensor([[81., 81., 81.],
        [81., 81., 81.],
        [81., 81., 81.]])
tensor([[81., 81., 81.],
        [81., 81., 81.],
        [81., 81., 81.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]]) tensor([[7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891],
        [7.3891, 7.3891, 7.3891]]) tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


### Approximation

* floor() ceil()
* round()
* trunc() frac()

In [80]:
import numpy as np

In [87]:
a = tf.constant(3.14)
print(tf.floor(a))
print(tf.math.ceil(a))
print(tf.math.round(a))
print(np.trunc(a.numpy()))
print(np.modf(a.numpy())[0])

tf.Tensor(3.0, shape=(), dtype=float32)
tf.Tensor(4.0, shape=(), dtype=float32)
tf.Tensor(3.0, shape=(), dtype=float32)
3.0
0.1400001


In [71]:
a = torch.tensor(3.14)
print(a.floor())
print(a.ceil())
print(a.round())
print(a.trunc())
print(a.frac())

tensor(3.)
tensor(4.)
tensor(3.)
tensor(3.)
tensor(0.1400)


### Statistics
* norm
* mean sum
* prod
* max, min, argmin, argmax ▪ kthvalue, topk

In [111]:
a = torch.full([8], 1)
b = a.reshape([2,4])
c = a.reshape([2,2,2])

print(b)
print(c)

# torch.norm()
print(b.norm(2))
print(c.norm(2))

print(b.norm(2, dim = 0))
print(b.norm(2, dim = 1))

print(c.norm(2, dim = 0).shape)
print(c.norm(2, dim = 1).shape)
print(c.norm(2, dim = 2).shape)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
tensor(2.8284)
tensor(2.8284)
tensor([1.4142, 1.4142, 1.4142, 1.4142])
tensor([2., 2.])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])


### Clamp


In [98]:
grad = tf.random.uniform([2,3], minval=15)

print(grad)

print(tf.reduce_max(grad))
print(tf.reduce_min(grad))

print(tf.clip_by_value(grad, 5,10))


tf.Tensor(
[[10.652033   5.9660015  2.4843903]
 [11.617971   3.1870842  5.1878815]], shape=(2, 3), dtype=float32)
tf.Tensor(11.617971, shape=(), dtype=float32)
tf.Tensor(2.4843903, shape=(), dtype=float32)
tf.Tensor(
[[10.         5.9660015  5.       ]
 [10.         5.         5.1878815]], shape=(2, 3), dtype=float32)


In [89]:
grad = torch.rand(2,3)*15

print(grad)

print(grad.max())
print(grad.min())

print(torch.clamp(grad, min=5, max=10))
print(grad.clamp(5,10))

tensor([[12.8346,  9.5469, 14.3791],
        [12.7299,  2.6548,  5.8642]])
tensor(14.3791)
tensor(2.6548)
tensor([[10.0000,  9.5469, 10.0000],
        [10.0000,  5.0000,  5.8642]])
tensor([[10.0000,  9.5469, 10.0000],
        [10.0000,  5.0000,  5.8642]])


### Broadcasting

Manully broadcast with `tf.broadcast_to` / `y.expand(*size)`.

Automatic broadcast in calculation.


In [17]:
x = tf.random.uniform([4,28,28,3])
y = tf.random.uniform([1,28,1,1])

print((tf.broadcast_to(y,[4,28,28,3])).shape)

print((x+y).shape)

(4, 28, 28, 3)
(4, 28, 28, 3)


In [18]:
x = torch.rand([4,3,28,28])
y = torch.rand([1,1,28,1])

print(y.expand(4,3,28,28).shape)

print((x+y).shape)

torch.Size([4, 3, 28, 28])
torch.Size([4, 3, 28, 28])


In [19]:
x = tf.random.uniform([4,28,28,3])
y = tf.random.uniform([4,28,1,1])

print((x + y).shape)

(4, 28, 28, 3)
